import { emptyLedger, uid, type Ledger } from './model.ts';
import { dates } from './engine.ts';
export const DEMO_DATE='2026-09-20';
export function demoLedger():Ledger{const l=emptyLedger('2026-06-01');l.profile={name:'Alex',trackingSince:'2026-06-01',coverageConfirmed:true,reserve:100000,savingsTarget:150000,semesterStart:'2026-07-01',semesterEnd:'2026-12-20'};l.checkpoint={date:'2026-09-19',amount:960000};
 const allowance=uid(),hostel=uid();l.schedules=[{id:allowance,name:'Monthly allowance',amount:1800000,type:'income',category:'other',date:'2026-06-01',cadence:'monthly',confirmed:true,active:true,skipped:[]},{id:hostel,name:'Hostel rent',amount:450000,type:'expense',category:'hostel',date:'2026-06-03',cadence:'monthly',confirmed:true,active:true,skipped:[]},{id:uid(),name:'Train home',amount:85000,type:'expense',category:'transport',date:'2026-09-26',cadence:'once',confirmed:true,active:true,skipped:[]},{id:uid(),name:'Semester materials',amount:120000,type:'expense',category:'academic',date:'2026-09-28',cadence:'once',confirmed:true,active:true,skipped:[]}];
 for(const d of dates('2026-06-01',DEMO_DATE)){const day=Number(d.slice(-2)),month=Number(d.slice(5,7));if(day===1)l.transactions.push({id:uid(),date:d,type:'income',amount:1800000,category:'other',merchant:'Family allowance',description:'Monthly student allowance',source:'demo',exceptional:false,scheduleId:allowance});if(day===3)l.transactions.push({id:uid(),date:d,type:'expense',amount:450000,category:'hostel',merchant:'Campus hostel',description:'Monthly rent',source:'demo',exceptional:false,scheduleId:hostel});
 if(day%3!==0)l.transactions.push({id:uid(),date:d,type:'expense',amount:(month===9?220:155)*100+(day%4)*2000,category:'food',merchant:day%2?'Campus café':'Mess lunch',description:'Lunch with classmates',source:'demo',exceptional:false});if(day%4===0)l.transactions.push({id:uid(),date:d,type:'expense',amount:16000,category:'transport',merchant:'Uber',description:'Ride to college',source:'demo',exceptional:false});if(day===12)l.transactions.push({id:uid(),date:d,type:'expense',amount:11900,category:'subscriptions',merchant:'Spotify',description:'Student subscription',source:'demo',exceptional:false});if(day===16)l.transactions.push({id:uid(),date:d,type:'expense',amount:35000,category:'entertainment',merchant:'PVR Cinemas',description:'Movie night',source:'demo',exceptional:false});}
 l.transactions.push({id:uid(),date:'2026-09-18',type:'expense',amount:85000,category:'food',merchant:'Café Coffee Day',description:'Dinner with friends',source:'demo',exceptional:false});
 for(const month of ['2026-06','2026-07','2026-08','2026-09'])l.budgets.push({month,category:null,amount:1350000},{month,category:'food',amount:400000},{month,category:'entertainment',amount:100000});
 const goal=uid();l.goals=[{id:goal,name:'A trip after finals',target:1200000,deadline:'2026-12-20',monthly:150000,priority:1}];l.allocations=[{id:uid(),goalId:goal,date:'2026-08-10',amount:200000},{id:uid(),goalId:goal,date:'2026-09-05',amount:150000}];return l;}
