import { type Ledger, type Transaction, type Scenario, rupees } from './model.ts';
export const METHOD='student-finance-v1';
export const dayMs=86400000;
export function addDays(d:string,n:number){return new Date(Date.parse(d+'T12:00:00Z')+n*dayMs).toISOString().slice(0,10);}
export function daysBetween(a:string,b:string){return Math.round((Date.parse(b)-Date.parse(a))/dayMs);}
export function monthStart(d:string){return d.slice(0,7)+'-01';}
export function monthEnd(d:string){const x=new Date(d+'T12:00:00Z');return new Date(Date.UTC(x.getUTCFullYear(),x.getUTCMonth()+1,0,12)).toISOString().slice(0,10);}
export function addMonths(d:string,n:number){const x=new Date(d+'T12:00:00Z');const first=new Date(Date.UTC(x.getUTCFullYear(),x.getUTCMonth()+n,1,12));const end=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0,12)).getUTCDate();first.setUTCDate(Math.min(x.getUTCDate(),end));return first.toISOString().slice(0,10);}
export function dates(a:string,b:string){const out:string[]=[];for(let d=a;d<=b;d=addDays(d,1)){out.push(d);if(out.length>4000)throw new Error('Date range too large');}return out;}
export function net(t:Transaction){return t.type==='expense'?t.amount:t.type==='refund'?-t.amount:0;}
export function cash(t:Transaction){return t.type==='expense'?-t.amount:t.amount;}
export function sum(ts:Transaction[]){return ts.reduce((a,t)=>a+net(t),0);}
export function between(l:Ledger,a:string,b:string){return l.transactions.filter(t=>t.date>=a&&t.date<=b);}
export function median(ns:number[]){if(!ns.length)return 0;const s=[...ns].sort((a,b)=>a-b);return s.length%2?s[Math.floor(s.length/2)]:(s[s.length/2-1]+s[s.length/2])/2;}
export function normalize(s:string){return s.toLowerCase().replace(/[^a-z0-9]/g,'');}
export type Occurrence={id:string;date:string;name:string;amount:number;type:'income'|'expense';category:string;paid:boolean};
export function occurrences(l:Ledger,from:string,to:string):Occurrence[]{
 const result:Occurrence[]=[];
 for(const s of l.schedules.filter(s=>s.active&&s.confirmed)){
  let d=s.date;let i=0;while(d<=to&&i<1000){
   if(d>=from&&!s.skipped.includes(d))result.push({id:s.id,date:d,name:s.name,amount:s.amount,type:s.type,category:s.category,paid:l.transactions.some(t=>t.scheduleId===s.id&&t.type===s.type&&Math.abs(daysBetween(d,t.date))<=(s.cadence==='weekly'?2:5))});
   i++;if(s.cadence==='once')break;d=s.cadence==='weekly'?addDays(s.date,i*7):addMonths(s.date,i*(s.cadence==='quarterly'?3:1));
  }
 }return result.sort((a,b)=>a.date.localeCompare(b.date));
}
export type Evidence={asOf:string;period:{from:string;to:string};comparison?:{from:string;to:string};revision:number;classification:'actual'|'forecast'|'scenario';method:string;formula:string;assumptions:string[];transactionIds:string[]};
export function evidence(l:Ledger,asOf:string,from:string,to:string,formula:string,classification:Evidence['classification']='actual'):Evidence{return {asOf,period:{from,to},revision:l.revision,classification,method:METHOD,formula,assumptions:['Recorded data only; missing transactions can change this result.'],transactionIds:between(l,from,to).map(t=>t.id)};}
export type Insight={id:string;title:string;body:string;kind:'trend'|'review'|'budget';category:string;impact:number;evidence:Evidence};
export function analyze(l:Ledger,asOf:string){
 const start=monthStart(asOf), end=monthEnd(asOf), priorStart=addMonths(start,-1), priorEnd=addMonths(asOf,-1);
 const current=between(l,start,asOf), previous=between(l,priorStart,priorEnd), actual=sum(current);
 const categoryTotals=l.categories.map(c=>({...c,amount:sum(current.filter(t=>t.category===c.id)),previous:sum(previous.filter(t=>t.category===c.id)),count:current.filter(t=>t.category===c.id&&t.type==='expense').length}));
 const totalBudget=l.budgets.find(b=>b.month===asOf.slice(0,7)&&b.category===null)?.amount??null;
 const trackingDays=l.profile.coverageConfirmed?Math.max(0,daysBetween(l.profile.trackingSince,asOf)):0;
 const historyStart=l.profile.trackingSince>addDays(asOf,-56)?l.profile.trackingSince:addDays(asOf,-56);
 const historyDays=historyStart<asOf?dates(historyStart,addDays(asOf,-1)):[];
 const historical=between(l,historyStart,addDays(asOf,-1)).filter(t=>!t.scheduleId&&!t.exceptional);
 const daily=historyDays.map(d=>({date:d,amount:Math.max(0,sum(historical.filter(t=>t.date===d)))}));
 const avg=daily.length?daily.reduce((a,d)=>a+d.amount,0)/daily.length:0;
 const rate=(d:string)=>{if(trackingDays<14)return 0;if(trackingDays<56)return Math.round(avg);const weekday=new Date(d).getUTCDay();const ds=daily.filter(x=>new Date(x.date).getUTCDay()===weekday);return Math.round(ds.reduce((a,x)=>a+x.amount,0)/Math.max(1,ds.length));};
 const unpaid=occurrences(l,l.profile.trackingSince,end).filter(o=>!o.paid&&o.date<=end);
 const future=unpaid.map(o=>({...o,date:o.date<asOf?asOf:o.date}));
 const committed=future.filter(o=>o.type==='expense').reduce((a,o)=>a+o.amount,0);
 const remainingDates=asOf<end?dates(addDays(asOf,1),end):[];
 const variable=remainingDates.reduce((a,d)=>a+rate(d),0), projected=actual+committed+variable;
 const currentBalance=l.checkpoint&&l.checkpoint.date<=asOf?l.checkpoint.amount+l.transactions.filter(t=>t.date>l.checkpoint!.date&&t.date<=asOf).reduce((a,t)=>a+cash(t),0):null;
 const allocated=l.allocations.filter(a=>a.date<=asOf).reduce((a,x)=>a+x.amount,0);
 const monthlyProtection=Math.max(l.profile.savingsTarget,l.goals.reduce((a,g)=>a+g.monthly,0));
 const alreadyContributed=l.allocations.filter(a=>a.date>=start&&a.date<=asOf).reduce((a,x)=>a+x.amount,0);
 const protectedAmount=l.profile.reserve+Math.max(0,allocated)+Math.max(0,monthlyProtection-alreadyContributed);
 let running=currentBalance??0; const timeline=[{date:asOf,balance:running}];
 for(const d of dates(asOf,end)){running+=future.filter(o=>o.date===d).reduce((a,o)=>a+(o.type==='income'?o.amount:-o.amount),0)-(d===asOf?0:rate(d));timeline.push({date:d,balance:running});}
 const cashHeadroom=currentBalance===null?null:Math.min(...timeline.map(t=>t.balance))-protectedAmount;
 const budgetHeadroom=totalBudget===null?null:totalBudget-actual-committed-Math.max(0,monthlyProtection-alreadyContributed);
 const constraints=[cashHeadroom,budgetHeadroom].filter((n):n is number=>n!==null);
 const headroom=constraints.length?Math.min(...constraints):null;
 const safeDaily=headroom===null?null:Math.floor(Math.max(0,headroom)/(daysBetween(asOf,end)+1));
 // Seeded resampling makes the illustrative range reproducible, never a calibrated probability.
 let range:{low:number;high:number}|null=null;
 if(trackingDays>=56&&daily.length>=56){let seed=17;const sample: number[]=[];for(let i=0;i<250;i++){let total=0;for(let j=0;j<remainingDates.length;j++){if(j%7===0)seed=(seed*16807)%2147483647;const week=seed%8;total+=daily[week*7+(j%7)]?.amount??avg;}sample.push(actual+committed+total);}sample.sort((a,b)=>a-b);range={low:Math.round(sample[25]),high:Math.round(sample[224])};}
 const insights:Insight[]=[];
 if(l.profile.coverageConfirmed&&l.profile.trackingSince<=priorStart)for(const c of categoryTotals){const diff=c.amount-c.previous;if(diff>0){const ev=evidence(l,asOf,start,asOf,'Current category net expenses − same elapsed period last month');ev.comparison={from:priorStart,to:priorEnd};ev.transactionIds=[...current,...previous].filter(t=>t.category===c.id).map(t=>t.id);const prevCount=previous.filter(t=>t.category===c.id&&t.type==='expense').length;insights.push({id:`trend:${c.id}:${asOf.slice(0,7)}:${Math.floor(diff/10000)}`,title:`${c.name} spending is increasing`,body:`${rupees(c.amount)} this month, ${c.previous>0?Math.round(diff/c.previous*100)+'% higher':rupees(diff)+' more'} than the same period last month. ${c.count} purchases versus ${prevCount}; compare transaction size and frequency.`,kind:'trend',category:c.id,impact:diff,evidence:ev});}}
 for(const t of current.filter(t=>t.type==='expense'&&!t.exceptional)){const peers=l.transactions.filter(p=>p.type==='expense'&&p.category===t.category&&p.date<t.date&&!p.exceptional);if(peers.length<20)continue;const med=median(peers.map(p=>p.amount)),mad=median(peers.map(p=>Math.abs(p.amount-med)));if(t.amount-med>Math.max(3*1.4826*mad,med,10000)){const ev=evidence(l,asOf,l.profile.trackingSince,t.date,'Amount > category median + max(3 × 1.4826 × MAD, median, ₹100)');ev.transactionIds=[t.id,...peers.map(p=>p.id)];insights.push({id:`review:${t.id}`,title:'A purchase worth reviewing',body:`${t.merchant}: ${rupees(t.amount)}, compared with a typical ${rupees(Math.round(med))} in this category. This may be an expected purchase.`,kind:'review',category:t.category,impact:t.amount-med,evidence:ev});}}
 if(totalBudget!==null&&projected>totalBudget)insights.push({id:`budget:${asOf.slice(0,7)}:${Math.floor((projected-totalBudget)/50000)}`,title:trackingDays>=14?'Your month may finish over budget':'Known commitments exceed your budget',body:`${rupees(projected)} ${trackingDays>=14?'projected':'in actuals and known commitments'} against ${rupees(totalBudget)} budget. Review ${rupees(projected-totalBudget)} of pressure.`,kind:'budget',category:'',impact:projected-totalBudget,evidence:evidence(l,asOf,start,end,'Actual + unpaid commitments + remaining variable daily estimates','forecast')});
 const chart=dates(start,end).map(d=>{const spent=sum(current.filter(t=>t.date<=d));return {date:d,label:Number(d.slice(-2)),actual:d<=asOf?spent:null,projected:d>=asOf?actual+future.filter(o=>o.type==='expense'&&o.date<=d).reduce((a,o)=>a+o.amount,0)+remainingDates.filter(x=>x<=d).reduce((a,x)=>a+rate(x),0):null,budget:totalBudget};});
 return {asOf,start,end,actual,previous:sum(previous),categoryTotals,totalBudget,trackingDays,projected,range,committed,variable,avg:Math.round(avg),safeDaily,headroom,cashHeadroom,budgetHeadroom,currentBalance,protectedAmount,timeline,chart,upcoming:unpaid,insights:insights.sort((a,b)=>b.impact-a.impact),evidence:evidence(l,asOf,start,end,'Actual + unpaid confirmed commitments + estimated variable spending','forecast')};
}
export type Analysis=ReturnType<typeof analyze>;
export function recurring(l:Ledger,asOf:string){const groups=new Map<string,Transaction[]>();for(const t of l.transactions.filter(t=>t.type==='expense'&&!t.scheduleId&&t.date<=asOf)){const key=normalize(t.merchant);groups.set(key,[...(groups.get(key)??[]),t]);}return [...groups.entries()].flatMap(([key,ts])=>{ts.sort((a,b)=>a.date.localeCompare(b.date));if(ts.length<3||l.schedules.some(s=>normalize(s.name)===key))return [];const recent=ts.slice(-4), gaps=recent.slice(1).map((t,i)=>daysBetween(recent[i].date,t.date)),m=median(gaps),amount=median(recent.map(t=>t.amount));const cadence=m>=5&&m<=9?'weekly':m>=26&&m<=34?'monthly':m>=85&&m<=96?'quarterly':null;if(!cadence||gaps.some(g=>Math.abs(g-m)>(cadence==='weekly'?2:6))||recent.some(t=>Math.abs(t.amount-amount)>amount*.2))return [];const last=recent.at(-1)!;return [{key,name:last.merchant,category:last.category,amount:Math.round(amount),cadence:cadence as 'weekly'|'monthly'|'quarterly',next:cadence==='weekly'?addDays(last.date,7):addMonths(last.date,cadence==='monthly'?1:3),ids:recent.map(t=>t.id)}];});}
export function budgetSuggestion(l:Ledger,asOf:string){const months=[1,2,3].map(n=>addMonths(monthStart(asOf),-n));if(!l.profile.coverageConfirmed||l.profile.trackingSince>months[2])return null;const incomes=occurrences(l,monthStart(asOf),monthEnd(asOf)).filter(o=>o.type==='income').reduce((a,o)=>a+o.amount,0);if(!incomes)return null;const protectedGoals=Math.max(l.profile.savingsTarget,l.goals.reduce((a,g)=>a+g.monthly,0));const fixed=occurrences(l,monthStart(asOf),monthEnd(asOf)).filter(o=>o.type==='expense');const base=l.categories.map(c=>({category:c.id,essential:c.essential,amount:Math.round(median(months.map(m=>Math.max(0,sum(between(l,m,monthEnd(m)).filter(t=>t.category===c.id&&!t.scheduleId)))))),fixed:fixed.filter(o=>o.category===c.id).reduce((a,o)=>a+o.amount,0)}));const essentials=base.reduce((a,c)=>a+c.fixed+(c.essential?c.amount:0),0),available=incomes-protectedGoals-essentials,flexible=base.filter(c=>!c.essential).reduce((a,c)=>a+c.amount,0);return {shortfall:Math.max(0,-available),income:incomes,protectedGoals,items:base.map(c=>({category:c.category,amount:c.fixed+(c.essential?c.amount:Math.floor(c.amount*Math.min(1,Math.max(0,available)/Math.max(1,flexible))))}))};}
export function simulate(l:Ledger,asOf:string,s:Scenario){const a=analyze(l,asOf);const history=between(l,addDays(asOf,-56),addDays(asOf,-1)).filter(t=>!t.scheduleId&&!t.exceptional);const dayCount=Math.max(1,Math.min(56,daysBetween(l.profile.trackingSince,asOf)));const catMonthly=Math.round(Math.max(0,sum(history.filter(t=>t.category===s.category)))/dayCount*30);const essential=l.categories.find(c=>c.id===s.category)?.essential;const scheduled=l.schedules.find(x=>x.id===s.scheduleId&&x.type==='expense'&&x.active);const effective=s.type==='reduction'?(essential?0:Math.min(s.amount,catMonthly)):s.type==='cancel'?(scheduled?.amount??0):s.amount;const all=occurrences(l,l.profile.trackingSince,addMonths(asOf,12)).filter(o=>!o.paid);let baseline=a.currentBalance??0,scenario=baseline;const series:{date:string;baseline:number;scenario:number}[]=[{date:asOf,baseline,scenario}];let expenseDelta=0;let allocatedDelta=0;
 const start=s.date<asOf?asOf:s.date;
 for(const d of dates(asOf,addMonths(asOf,12))){const os=all.filter(o=>(o.date<asOf?asOf:o.date)===d);baseline+=os.reduce((x,o)=>x+(o.type==='income'?o.amount:-o.amount),0)-(d===asOf?0:a.avg);scenario+=os.reduce((x,o)=>x+(o.type==='income'?o.amount:-o.amount),0)-(d===asOf?0:a.avg);
 if(d>=start){let delta=0;if(s.type==='purchase'&&d===start){delta=-effective;expenseDelta+=effective;}if(s.type==='reduction'&&d>asOf){delta=effective/(Number(monthEnd(d).slice(-2)));expenseDelta-=delta;}if(s.type==='cancel'){delta=os.filter(o=>o.id===s.scheduleId).reduce((x,o)=>x+o.amount,0);expenseDelta-=delta;}if((s.type==='allowance'||s.type==='goal')&&d===addMonths(start,(Number(d.slice(0,4))-Number(start.slice(0,4)))*12+Number(d.slice(5,7))-Number(start.slice(5,7)))){if(s.type==='allowance')delta=effective;else allocatedDelta+=effective;}scenario+=delta;}
 series.push({date:d,baseline:Math.round(baseline),scenario:Math.round(scenario)});
 }
 const horizons=[1,3,6,12].map(months=>{const end=addMonths(asOf,months);const p=series.findLast(x=>x.date===end)!;return {months,...p,change:p.scenario-p.baseline};});
 const goal=l.goals[0];const saved=goal?l.allocations.filter(x=>x.goalId===goal.id&&x.date<=asOf).reduce((v,x)=>v+x.amount,0):0;const remaining=goal?Math.max(0,goal.target-saved):0;const baselineContribution=goal?.monthly??0;const monthlyGain=s.type==='reduction'?effective:s.type==='allowance'?effective:s.type==='cancel'&&scheduled?(scheduled.cadence==='monthly'?effective:scheduled.cadence==='weekly'?effective*52/12:scheduled.cadence==='quarterly'?effective/3:0):0;
 return {effective,limited:effective!==s.amount,series:series.filter((p,i)=>i===0||p.date.endsWith('-01')||p.date===monthEnd(asOf)||p.date===start),horizons,firstShortfall:a.currentBalance===null?null:series.find(p=>p.scenario<a.protectedAmount)?.date??null,monthEnd:series.findLast(x=>x.date===monthEnd(asOf)),expenseDelta:Math.round(expenseDelta),allocatedDelta,goal:goal?{name:goal.name,baselineMonths:baselineContribution>0?Math.ceil(remaining/baselineContribution):null,scenarioMonths:baselineContribution+monthlyGain>0?Math.ceil((remaining+(s.type==='purchase'?effective:0))/(baselineContribution+monthlyGain)):null}:null,evidence:evidence(l,asOf,asOf,addMonths(asOf,12),'Dated cash flows + constant historical daily variable spending + selected scenario changes','scenario')};}
export function health(l:Ledger,a:Analysis){const goalMonthly=l.goals.reduce((v,g)=>v+g.monthly,0);const contributions=l.allocations.filter(x=>x.date>=a.start&&x.date<=a.asOf).reduce((v,x)=>v+x.amount,0);const os=occurrences(l,a.start,a.end);const income=os.filter(x=>x.type==='income').reduce((v,x)=>v+x.amount,0);const recurringLoad=os.filter(x=>x.type==='expense').reduce((v,x)=>v+x.amount,0);const weekly=[1,2,3,4].map(i=>sum(between(l,addDays(a.asOf,-i*7),addDays(a.asOf,-(i-1)*7-1))));const historic=l.budgets.filter(b=>b.category===null&&b.month<a.asOf.slice(0,7)&&b.month+'-01'>=l.profile.trackingSince);const over=historic.filter(b=>sum(between(l,b.month+'-01',monthEnd(b.month+'-01')))>b.amount).length;return [{name:'Budget adherence',value:a.totalBudget===null?'Set a budget':a.projected>a.totalBudget?'Under pressure':'On track',detail:a.totalBudget===null?'No monthly limit yet.':`${rupees(a.actual)} recorded of ${rupees(a.totalBudget)}; outlook ${rupees(a.projected)}.`},{name:'Saving consistency',value:goalMonthly?`${Math.round(contributions/goalMonthly*100)}% contributed`:'No contribution plan',detail:`${rupees(contributions)} allocated this month. Recorded surplus is not assumed to be saved.`},{name:'Spending consistency',value:a.trackingDays>=28?`${rupees(Math.min(...weekly))}–${rupees(Math.max(...weekly))}`:'More history needed',detail:'Range across four completed seven-day periods. Variation is not a judgment.'},{name:'Recurring load',value:income?`${Math.round(recurringLoad/income*100)}% of planned income`:'Income not defined',detail:`${rupees(recurringLoad)} of scheduled expenses this month.`},{name:'Overspending frequency',value:historic.length?`${over} of ${historic.length} months`:'More history needed',detail:'Completed months with both a budget and confirmed tracking coverage.'},{name:'Emergency buffer',value:rupees(l.profile.reserve),detail:'Funds you explicitly marked as protected; not inferred from income.'},{name:'Upcoming pressure',value:a.cashHeadroom===null?'Balance needed':a.cashHeadroom<0?'Projected shortfall':'Covered in model',detail:a.cashHeadroom===null?'Add an end-of-day cash checkpoint.':`${rupees(a.cashHeadroom)} minimum projected headroom after protected funds.`}];}
