import Papa from 'papaparse';
import { type Ledger, type Transaction, ledgerSchema, transactionSchema, uid, paise } from './model.ts';
export type Mapping={date:string;amount:string;merchant:string;category:string;type:string};
export function csvRows(text:string){const parsed=Papa.parse<Record<string,string>>(text,{header:true,skipEmptyLines:'greedy'});if(parsed.errors.length)throw new Error('CSV could not be parsed: '+parsed.errors[0].message);if(parsed.data.length>10000)throw new Error('Import at most 10,000 rows at once.');return {headers:parsed.meta.fields??[],rows:parsed.data};}
export function previewImport(rows:Record<string,string>[],m:Mapping,l:Ledger,asOf:string){return rows.map((r,i)=>{try{const type=r[m.type]?.toLowerCase()||'expense';const category=l.categories.find(c=>c.id===r[m.category]?.toLowerCase()||c.name.toLowerCase()===r[m.category]?.toLowerCase())?.id??'other';const t=transactionSchema.parse({id:uid(),date:r[m.date]?.trim(),amount:paise(r[m.amount]?.replaceAll(',','').replace('₹','').trim()),merchant:r[m.merchant]?.trim(),category,type,description:'CSV import',source:'csv',exceptional:false});if(t.date>asOf)throw new Error('Future entries belong in planned commitments.');const duplicate=l.transactions.some(x=>x.date===t.date&&x.amount===t.amount&&x.merchant.toLowerCase()===t.merchant.toLowerCase()&&x.type===t.type);return {row:i+2,transaction:t,duplicate,error:null};}catch(e){return {row:i+2,transaction:null,duplicate:false,error:e instanceof Error?e.message:'Invalid row'};}});}
export async function fingerprint(text:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
export function backup(l:Ledger){return JSON.stringify({format:'pocketwise-backup',exportedAt:new Date().toISOString(),ledger:l},null,2);}
export function restore(text:string){const parsed=JSON.parse(text);if(parsed.format!=='pocketwise-backup')throw new Error('Choose a Pocketwise backup.');return ledgerSchema.parse(parsed.ledger);}
export function exportCSV(ts:Transaction[]){const escape=(s:string)=>/^[=+\-@\t\r]/.test(s)?"'"+s:s;return Papa.unparse(ts.map(t=>({date:t.date,type:t.type,amount:(t.amount/100).toFixed(2),merchant:escape(t.merchant),category:t.category,description:escape(t.description)})));}
