import { type Ledger, type Transaction, uid, paise, rupees } from './model.ts';
import { analyze, between, sum, monthStart, addMonths, addDays, daysBetween, evidence, type Evidence } from './engine.ts';
export function parseExpense(text:string,asOf:string):{draft:Transaction;warnings:string[]}{
 const amounts=[...text.matchAll(/(?:₹\s*|rs\.?\s*)?(\d+(?:,\d{3})*(?:\.\d{1,2})?)/gi)];if(amounts.length!==1)throw new Error('Enter one amount, or use the manual form to clarify multiple numbers.');const amount=paise(amounts[0][1].replaceAll(',',''));if(!amount)throw new Error('Amount must be greater than zero');const lower=text.toLowerCase();const rules:[RegExp,string][]=[[/lunch|dinner|food|café|cafe|ccd|coffee|breakfast|swiggy|zomato/,'food'],[/uber|bus|train|metro|ola|transport/,'transport'],[/headphone|bought|shopping|clothes/,'shopping'],[/spotify|netflix|subscription|recharge/,'subscriptions'],[/movie|cinema|concert/,'entertainment'],[/hostel|rent/,'hostel'],[/book|college fee|academic|stationery/,'academic']];const category=rules.find(([r])=>r.test(lower))?.[1]??'other';const merchant=text.replace(amounts[0][0],'').replace(/\b(had|bought|for|today|yesterday|paid)\b/gi,'').trim().slice(0,120)||'Expense';return {draft:{id:uid(),date:/yesterday/i.test(text)?addDays(asOf,-1):asOf,type:'expense',amount,category,merchant,description:text.slice(0,500),source:'language',exceptional:false},warnings:[...(category==='other'?['Category needs your review.']:[]),'Review merchant, date, and amount before saving.']};
}
export type Answer={title:string;text:string;evidence:Evidence|null;scenarioAmount?:number};
export function answerQuestion(l:Ledger,asOf:string,q:string):Answer{
 const a=analyze(l,asOf),text=q.toLowerCase();let from=monthStart(asOf),to=asOf;
 if(/last week/.test(text)){const weekday=(new Date(asOf).getUTCDay()+6)%7;to=addDays(asOf,-weekday-1);from=addDays(to,-6);}else if(/last month/.test(text)){from=addMonths(monthStart(asOf),-1);to=addDays(monthStart(asOf),-1);}else if(/semester/.test(text)){if(!l.profile.semesterStart||!l.profile.semesterEnd)return {title:'Define your semester',text:'Add semester start and end dates in Settings to use this period.',evidence:null};from=l.profile.semesterStart;to=l.profile.semesterEnd<asOf?l.profile.semesterEnd:asOf;}
 const ev=evidence(l,asOf,from,to,'Sum of authorized recorded expenses minus refunds for the selected dates');
 if(/can i|afford|what if/.test(text)){const match=text.match(/(?:₹|rs\.?\s*)?(\d[\d,]*(?:\.\d{1,2})?)/);return {title:'Try this decision',text:a.currentBalance===null?'Add a cash checkpoint to assess affordability. You can still compare spending scenarios.':`Model headroom is ${rupees(a.headroom??0)} after commitments and protected funds. Run the dated scenario to inspect its effect; this is an estimate.`,evidence:a.evidence,scenarioAmount:match?paise(match[1].replaceAll(',','')):200000};}
 if(/safe|today|headroom/.test(text))return {title:a.currentBalance===null?'Budget headroom':'Estimated daily headroom',text:a.safeDaily===null?'Add a monthly budget or cash checkpoint first.':`${rupees(a.safeDaily)} per remaining day under current assumptions. ${a.currentBalance===null?'This does not establish cash affordability.':'Check upcoming cash flows before making a commitment.'}`,evidence:a.evidence};
 if(/subscription|recurring|upcoming/.test(text))return {title:'Confirmed upcoming commitments',text:a.upcoming.filter(o=>o.type==='expense').map(o=>`${o.name}: ${rupees(o.amount)} on ${o.date}`).join('; ')||'No confirmed unpaid commitments. Detected candidates are available in Explore.',evidence:a.evidence};
 if(/save|goal/.test(text)){const g=l.goals[0];if(!g)return {title:'Set a goal first',text:'Add a target and deadline in Plan to calculate a contribution schedule.',evidence:null};const saved=l.allocations.filter(x=>x.goalId===g.id&&x.date<=asOf).reduce((v,x)=>v+x.amount,0),weeks=Math.max(0,daysBetween(asOf,g.deadline)/7);return {title:g.name,text:weeks>0?`You have allocated ${rupees(saved)} of ${rupees(g.target)}. Reaching the target requires approximately ${rupees(Math.ceil(Math.max(0,g.target-saved)/weeks))} per week until ${g.deadline}. This is a required contribution, not a promise of affordability.`:'The deadline has passed. Update the goal before planning further contributions.',evidence:ev};}
 if(/why|compare|increas|growing|changed/.test(text)){const top=a.categoryTotals.slice().sort((x,y)=>(y.amount-y.previous)-(x.amount-x.previous))[0];if(!l.profile.coverageConfirmed||l.profile.trackingSince>addMonths(monthStart(asOf),-1))return {title:'Comparable history needed',text:'Confirm coverage of this month and the previous comparison period before explaining a change.',evidence:null};const comparison={from:addMonths(from,-1),to:addMonths(to,-1)};return {title:'What changed this month',text:`${rupees(a.actual)} recorded this month versus ${rupees(a.previous)} over the same elapsed period last month. ${top?.name??'No category'} has the largest rupee change (${rupees((top?.amount??0)-(top?.previous??0))}). This describes contribution, not a personal cause.`,evidence:{...ev,comparison,transactionIds:[...between(l,from,to),...between(l,comparison.from,comparison.to)].map(t=>t.id)}};}
 const category=l.categories.find(c=>text.includes(c.name.split(' ')[0].toLowerCase()));const merchants=[...new Set(l.transactions.map(t=>t.merchant))];const merchant=merchants.find(m=>text.includes(m.toLowerCase()));let tx=between(l,from,to);if(category)tx=tx.filter(t=>t.category===category.id);if(merchant)tx=tx.filter(t=>t.merchant===merchant);
 if(category||merchant||/spend|spent|most|total/.test(text)){if(/most/.test(text)){const totals=l.categories.map(c=>({name:c.name,total:sum(tx.filter(t=>t.category===c.id))})).sort((x,y)=>y.total-x.total);return {title:'Largest spending category',text:tx.length?`${totals[0].name}: ${rupees(totals[0].total)} from ${from} to ${to}.`:'No recorded transactions in this period.',evidence:ev};}return {title:merchant??category?.name??'Recorded spending',text:`${rupees(sum(tx))} net spending from ${from} to ${to}, based on ${tx.length} recorded transactions.`,evidence:{...ev,transactionIds:tx.map(t=>t.id)}};}
 return {title:'Choose a supported financial question',text:'I can total spending, compare periods, review commitments, calculate goal contributions, or open a scenario. I cannot infer missing transactions or give investment advice.',evidence:null};
}
