import { z } from 'zod';
export const dateSchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v => !isNaN(Date.parse(v)) && new Date(v).toISOString().slice(0,10) === v, 'Use a valid date');
export const moneySchema = z.number().int().min(0).max(1_000_000_000);
export const categorySchema = z.object({ id:z.string().min(1), name:z.string().min(1).max(50), essential:z.boolean(), color:z.string().regex(/^#[0-9a-f]{6}$/i) });
export const transactionSchema = z.object({ id:z.string().uuid(), date:dateSchema, type:z.enum(['expense','income','refund']), amount:moneySchema.refine(v=>v>0), category:z.string(), merchant:z.string().trim().min(1).max(120), description:z.string().max(500), source:z.enum(['manual','language','csv','demo']), exceptional:z.boolean().default(false), refundOf:z.string().uuid().optional(), scheduleId:z.string().uuid().optional() });
export const scheduleSchema=z.object({id:z.string().uuid(), name:z.string().min(1).max(120), amount:moneySchema.refine(v=>v>0), type:z.enum(['expense','income']), category:z.string(), date:dateSchema, cadence:z.enum(['once','weekly','monthly','quarterly']), confirmed:z.boolean(), active:z.boolean(), skipped:z.array(dateSchema).default([])});
export const goalSchema=z.object({id:z.string().uuid(),name:z.string().min(1).max(80),target:moneySchema.refine(v=>v>0),deadline:dateSchema,monthly:moneySchema,priority:z.number().int().min(1).max(5)});
export const allocationSchema=z.object({id:z.string().uuid(),goalId:z.string().uuid(),date:dateSchema,amount:z.number().int().min(-1_000_000_000).max(1_000_000_000)});
export const scenarioSchema=z.object({id:z.string().uuid(),name:z.string().min(1).max(100),type:z.enum(['purchase','reduction','allowance','cancel','goal']),amount:moneySchema,category:z.string(),date:dateSchema,scheduleId:z.string().optional()});
export const ledgerSchema=z.object({version:z.literal(1),revision:z.number().int().nonnegative(),profile:z.object({name:z.string().max(60),trackingSince:dateSchema,coverageConfirmed:z.boolean(),semesterStart:dateSchema.optional(),semesterEnd:dateSchema.optional(),reserve:moneySchema,savingsTarget:moneySchema}),categories:z.array(categorySchema).max(100),transactions:z.array(transactionSchema).max(50000),budgets:z.array(z.object({month:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/),category:z.string().nullable(),amount:moneySchema})).max(5000),checkpoint:z.object({date:dateSchema,amount:moneySchema}).nullable(),schedules:z.array(scheduleSchema).max(1000),goals:z.array(goalSchema).max(100),allocations:z.array(allocationSchema).max(10000),scenarios:z.array(scenarioSchema).max(100),preferences:z.object({aiConsent:z.boolean(),alerts:z.boolean(),mutedCategories:z.array(z.string()),dismissed:z.array(z.string()),snoozedUntil:dateSchema.nullable()}),imports:z.array(z.string()).max(1000)}).superRefine((l,ctx)=>{
 const cats=new Set(l.categories.map(c=>c.id)); const ids=new Set(l.transactions.map(t=>t.id)); const goals=new Set(l.goals.map(g=>g.id)); const schedules=new Set(l.schedules.map(s=>s.id));
 if(ids.size!==l.transactions.length)ctx.addIssue({code:'custom',message:'Duplicate transaction IDs'});
 for(const t of l.transactions){if(!cats.has(t.category))ctx.addIssue({code:'custom',message:'Unknown transaction category'});if(t.refundOf&&!ids.has(t.refundOf))ctx.addIssue({code:'custom',message:'Refund reference is missing'});if(t.scheduleId&&!schedules.has(t.scheduleId))ctx.addIssue({code:'custom',message:'Schedule reference is missing'});}
 for(const a of l.allocations)if(!goals.has(a.goalId))ctx.addIssue({code:'custom',message:'Goal reference is missing'});
 const keys=l.budgets.map(b=>b.month+':'+b.category);if(new Set(keys).size!==keys.length)ctx.addIssue({code:'custom',message:'Duplicate budget'});
 for(const b of l.budgets)if(b.category&&!cats.has(b.category))ctx.addIssue({code:'custom',message:'Unknown budget category'});
});
export type Ledger=z.infer<typeof ledgerSchema>; export type Transaction=z.infer<typeof transactionSchema>;export type Schedule=z.infer<typeof scheduleSchema>;export type Scenario=z.infer<typeof scenarioSchema>;
export const categories:Ledger['categories']=[{id:'food',name:'Food & cafés',essential:false,color:'#db9563'},{id:'transport',name:'Transport',essential:true,color:'#789991'},{id:'shopping',name:'Shopping',essential:false,color:'#aaa0cb'},{id:'subscriptions',name:'Subscriptions',essential:false,color:'#d8bd71'},{id:'entertainment',name:'Entertainment',essential:false,color:'#cb8496'},{id:'hostel',name:'Hostel & living',essential:true,color:'#749ab8'},{id:'academic',name:'Academic',essential:true,color:'#9cae70'},{id:'other',name:'Other',essential:false,color:'#9aa29d'}];
export function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
export function emptyLedger(asOf=today()):Ledger{return {version:1,revision:0,profile:{name:'Student',trackingSince:asOf,coverageConfirmed:false,reserve:0,savingsTarget:0},categories:structuredClone(categories),transactions:[],budgets:[],checkpoint:null,schedules:[],goals:[],allocations:[],scenarios:[],preferences:{aiConsent:false,alerts:true,mutedCategories:[],dismissed:[],snoozedUntil:null},imports:[]};}
export const uid=()=>crypto.randomUUID();
export function rupees(v:number){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:v%100?2:0}).format(v/100);}
export function paise(v:string|number){const s=String(v).trim();if(!/^\d+(\.\d{1,2})?$/.test(s))throw new Error('Enter a positive amount with at most two decimal places');const [a,b='']=s.split('.');return moneySchema.parse(Number(a)*100+Number(b.padEnd(2,'0')));}
