import { useEffect, useRef, type ReactNode } from 'react';
import { X, ArrowUpRight, Info, Check, Plus, ShieldCheck } from 'lucide-react';
import { type Ledger, rupees } from './domain/model';
import type { Evidence } from './domain/engine';
export type Mutate=(fn:(l:Ledger)=>void)=>Promise<boolean>;
export function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const el=ref.current;el?.showModal();return()=>el?.close();},[]);return <dialog ref={ref} className={wide?'modal wide':'modal'} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}} aria-label={title}><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={20}/></button></div>{children}</dialog>;}
export function EvidenceModal({value,ledger,onClose}:{value:Evidence;ledger:Ledger;onClose:()=>void}){return <Modal title="Why am I seeing this?" onClose={onClose} wide><div className="evidence-label"><ShieldCheck size={17}/> Calculated from your records · {value.classification}</div><dl className="facts"><dt>Period</dt><dd>{value.period.from} → {value.period.to}</dd>{value.comparison&&<><dt>Comparison</dt><dd>{value.comparison.from} → {value.comparison.to}</dd></>}<dt>Calculation</dt><dd>{value.formula}</dd><dt>As of</dt><dd>{value.asOf} · Asia/Kolkata</dd><dt>Method</dt><dd>{value.method} · revision {value.revision}</dd></dl><div className="notice">{value.assumptions.join(' ')} Predictions are estimates, not guaranteed outcomes.</div><h3>Source transactions ({value.transactionIds.length})</h3><div className="evidence-list">{ledger.transactions.filter(t=>value.transactionIds.includes(t.id)).sort((a,b)=>b.date.localeCompare(a.date)).map(t=><div className="list-row" key={t.id}><span><strong>{t.merchant}</strong><small>{t.date} · {t.type}</small></span><b>{rupees(t.amount)}</b></div>)}{!value.transactionIds.length&&<p>No actual transactions in this period. Check the planned commitments and assumptions.</p>}</div></Modal>;}
export function Why({onClick}:{onClick:()=>void}){return <button className="text-button why" onClick={onClick}><Info size={13}/> Why am I seeing this?</button>;}
export function Empty({title,children}:{title:string;children?:ReactNode}){return <div className="empty"><div className="empty-symbol"><Plus/></div><h3>{title}</h3>{children}</div>;}
export function SectionTitle({eyebrow,title,children}:{eyebrow?:string;title:string;children?:ReactNode}){return <div className="section-title"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{children}</div>;}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{tone==='green'&&<Check size={12}/>} {children}</span>;}
export function LinkButton({children,onClick}:{children:ReactNode;onClick:()=>void}){return <button className="text-button" onClick={onClick}>{children}<ArrowUpRight size={15}/></button>;}
export function download(name:string,content:string,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function readableError(e:unknown){return e instanceof Error?e.message:'Something went wrong. Please retry.';}
